wireplumber.components = [
  {
    name = "51-rmf-audio-on-bluez.lua"
    type = "script/lua"
    provides = custom.rmf-audio-monitor
  }
]

wireplumber.profiles = {
  main = {
    custom.rmf-audio-monitor = required
  }
}
